apiVersion: v1
kind: Service
metadata:
  name: hf-api-svc
spec:
  type: ClusterIP
  selector:
    app: hf-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hf-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hf-api
  template:
    metadata:
      labels:
        app: hf-api
    spec:
      containers:
      - name: hf-api
        image: 211125418324.dkr.ecr.ap-northeast-2.amazonaws.com/huggingface
        ports:
        - containerPort: 8080

